version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["--env", "production"]
    container_name: pomodoro-todo-bot_node
    restart: on-failure
    volumes:
      - ./app:/bot
      - /bot/node_modules
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    environment:
      - USE_DOCKER
      - "FORCE_SSL=yes"
    env_file:
      - .env
  redis:
    image: redis:5.0.3-alpine
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    container_name: pomodoro-todo-bot_redis
    hostname: redis
    volumes:
      - ./data:/data/redis
    ports:
      - "${REDIS_PORT}:6379"
  logger:
    image: gliderlabs/logspout:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: 'syslog+tls://${LOGGER}'
    restart: always
volumes:
  # for persistence between restarts
  redis-data: {}
  data:
    driver: local