FROM node:10

RUN mkdir /bot

COPY app /bot

WORKDIR /bot

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

RUN yarn install --network-timeout 100000
RUN yarn build
RUN yarn global add pm2@latest typescript --network-timeout 100000

EXPOSE 3000

ENTRYPOINT ["pm2-runtime", "ecosystem.config.js"]